spring:
  application:
    name: architecture

  datasource:
    hikari:
      minimum-idle: 20      # ?? ??? ?? (idle ??)
      maximum-pool-size: 50 # ?? ?? ? ??
      idle-timeout: 30000   # idle ??? ??? ??? ???? ?? (???)
      connection-timeout: 30000 # ??? ?? ?? ?? ?? ?? (???)
      max-lifetime: 1800000 # ??? ?? ?? (???)


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
