services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
    ports:
      - '55432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 512M
